void swap(int *a, int  *b);
int mystrlen(const char *s);
int ispalimdrome(const char *s);
char *reverse(char *s);
int raiseit(char *s);
void memswap(void *a, void *b);
int **matadd(int **a, int **b, int **r);
int **matsub(int **a, int **b, int **r);
int **matmul(int **a, int **b, int **r);
int **matscalmul(int **a, int b, int **r);
int **matalloc(unsigned int n, int v);
void printmat(int **r, int lin, int col);
void initmatc(int **r, int n, int v);
void matfree(int **m, int n);
