char *my_strupcase(char *str);
char *my_str(char *str);
int my_strlen(const char *str);
char *my_strlowcase(char *str);
int my_strcmp(const char *s1, const char *s2);
int my_strncmp(const char *s1, const char *s2, unsigned int n);
char *my_strdup(const char *s);
char *my_strcpy(char *dest, const char *src);
char *my_strncpy(char *dest, const char *src, unsigned int n);
int my_atoi(const char *ptr);
int my_atoi_base(const char *str, const char *base);
unsigned long int my_strtoul(const char *nptr, const char **endptr, int base);
char **my_strarray(char *string, char *delimiter);
const  char *my_strstr(const char *big, const  char *little);
char *my_strcat(char *s, const char *append);
char *my_itoa(int value, char *str, int base);
