# Generated by Django 5.0.7 on 2024-08-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='like_news',
            field=models.BooleanField(default=False),
        ),
    ]
