# Generated by Django 5.0.7 on 2024-08-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_band_like_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='like_news',
        ),
        migrations.AddField(
            model_name='listing',
            name='like_news',
            field=models.BooleanField(default=False),
        ),
    ]
