# Generated by Django 5.0.7 on 2024-08-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_band_like_news_listing_like_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='like_news',
        ),
    ]
