version: "2.7"
services:
  app:
    build: ./app
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: mysql:8.1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
